-- SplitFlow Database Schema and Security Policies
-- This file contains the complete tables, triggers, and RLS policies.

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

---------------------------------------------------------
-- 1. TABLES
---------------------------------------------------------

-- Users Table (linked to auth.users)
CREATE TABLE IF NOT EXISTS public.users (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  share_id TEXT UNIQUE, -- Automatically generated by trigger
  avatar_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Groups Table
CREATE TABLE IF NOT EXISTS public.groups (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  created_by UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Group Members Junction Table
CREATE TABLE IF NOT EXISTS public.group_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  group_id UUID NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(group_id, user_id)
);

-- Expenses Table
CREATE TABLE IF NOT EXISTS public.expenses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  group_id UUID NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  category TEXT NOT NULL DEFAULT 'others',
  notes TEXT,
  paid_by UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  receipt_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Expense Splits Table
CREATE TABLE IF NOT EXISTS public.expense_splits (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  expense_id UUID NOT NULL REFERENCES public.expenses(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  amount NUMERIC(12, 2) NOT NULL CHECK (amount >= 0),
  split_value NUMERIC(12, 2) NOT NULL CHECK (split_value >= 0),
  UNIQUE(expense_id, user_id)
);

-- Settlements Table
CREATE TABLE IF NOT EXISTS public.settlements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  group_id UUID NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  from_user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  to_user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT different_users CHECK (from_user_id <> to_user_id)
);

---------------------------------------------------------
-- 2. TRIGGERS & FUNCTIONS
---------------------------------------------------------

-- Function to generate a unique Share ID (e.g. SF-7KX2M9)
CREATE OR REPLACE FUNCTION public.generate_share_id()
RETURNS trigger AS $$
DECLARE
  new_id TEXT;
  done BOOL;
  chars TEXT := 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  i INT;
BEGIN
  done := false;
  WHILE NOT done LOOP
    new_id := 'SF-';
    FOR i IN 1..6 LOOP
      new_id := new_id || substr(chars, floor(random() * length(chars) + 1)::int, 1);
    END LOOP;
    
    -- Check for uniqueness in the users table
    IF NOT EXISTS (SELECT 1 FROM public.users WHERE share_id = new_id) THEN
      done := true;
    END IF;
  END LOOP;
  NEW.share_id := new_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to run before insert on users
CREATE OR REPLACE TRIGGER on_user_before_insert
  BEFORE INSERT ON public.users
  FOR EACH ROW
  EXECUTE FUNCTION public.generate_share_id();

-- Function to handle new user signup from auth schema
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.users (id, name, email, avatar_url)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    new.email,
    new.raw_user_meta_data->>'avatar_url'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to run after new auth.user is created
CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- Function to automatically add the creator of a group as a member
CREATE OR REPLACE FUNCTION public.auto_add_creator_to_members()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.group_members (group_id, user_id)
  VALUES (NEW.id, NEW.created_by)
  ON CONFLICT (group_id, user_id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to run after a new group is created
CREATE OR REPLACE TRIGGER on_group_created
  AFTER INSERT ON public.groups
  FOR EACH ROW
  EXECUTE FUNCTION public.auto_add_creator_to_members();

-- SECURITY DEFINER Function to check membership (Bypasses RLS recursion)
CREATE OR REPLACE FUNCTION public.is_group_member(group_uuid UUID, user_uuid UUID)
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.group_members
    WHERE group_id = group_uuid AND user_id = user_uuid
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Helper to safely cast text to UUID for storage paths
CREATE OR REPLACE FUNCTION public.safe_cast_uuid(text_val TEXT)
RETURNS uuid AS $$
BEGIN
  RETURN text_val::uuid;
EXCEPTION WHEN others THEN
  RETURN null;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

---------------------------------------------------------
-- 3. ROW LEVEL SECURITY (RLS) POLICIES
---------------------------------------------------------

-- Enable RLS on all tables
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expense_splits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settlements ENABLE ROW LEVEL SECURITY;

-- 3.1 Users Policies
DROP POLICY IF EXISTS "Allow anyone authenticated to view profiles" ON public.users;
CREATE POLICY "Allow anyone authenticated to view profiles"
  ON public.users FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Allow users to insert their own profile" ON public.users;
CREATE POLICY "Allow users to insert their own profile"
  ON public.users FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Allow users to update their own profile" ON public.users;
CREATE POLICY "Allow users to update their own profile"
  ON public.users FOR UPDATE TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- 3.2 Groups Policies
DROP POLICY IF EXISTS "Allow group members to view groups" ON public.groups;
CREATE POLICY "Allow group members to view groups"
  ON public.groups FOR SELECT TO authenticated
  USING (
    id IN (SELECT group_id FROM public.group_members WHERE user_id = auth.uid())
  );

DROP POLICY IF EXISTS "Allow users to create groups" ON public.groups;
CREATE POLICY "Allow users to create groups"
  ON public.groups FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = created_by);

DROP POLICY IF EXISTS "Allow group members to update group details" ON public.groups;
CREATE POLICY "Allow group members to update group details"
  ON public.groups FOR UPDATE TO authenticated
  USING (
    id IN (SELECT group_id FROM public.group_members WHERE user_id = auth.uid())
  );

DROP POLICY IF EXISTS "Allow creator to delete groups" ON public.groups;
CREATE POLICY "Allow creator to delete groups"
  ON public.groups FOR DELETE TO authenticated
  USING (created_by = auth.uid());

-- 3.3 Group Members Policies
DROP POLICY IF EXISTS "Allow members to view group member lists" ON public.group_members;
CREATE POLICY "Allow members to view group member lists"
  ON public.group_members FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Allow members to invite or join group" ON public.group_members;
CREATE POLICY "Allow members to invite or join group"
  ON public.group_members FOR INSERT TO authenticated
  WITH CHECK (
    -- User is joining themselves
    auth.uid() = user_id 
    OR 
    -- Or user is already a member of the group
    group_id IN (SELECT gm.group_id FROM public.group_members gm WHERE gm.user_id = auth.uid())
    OR
    -- Or user is the creator of the group
    group_id IN (SELECT g.id FROM public.groups g WHERE g.created_by = auth.uid())
  );

DROP POLICY IF EXISTS "Allow members to leave or creator to remove member" ON public.group_members;
CREATE POLICY "Allow members to leave or creator to remove member"
  ON public.group_members FOR DELETE TO authenticated
  USING (
    user_id = auth.uid() 
    OR 
    group_id IN (SELECT g.id FROM public.groups g WHERE g.created_by = auth.uid())
  );

-- 3.4 Expenses Policies
DROP POLICY IF EXISTS "Allow members to view group expenses" ON public.expenses;
CREATE POLICY "Allow members to view group expenses"
  ON public.expenses FOR SELECT TO authenticated
  USING (
    group_id IN (SELECT gm.group_id FROM public.group_members gm WHERE gm.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "Allow members to create group expenses" ON public.expenses;
CREATE POLICY "Allow members to create group expenses"
  ON public.expenses FOR INSERT TO authenticated
  WITH CHECK (
    group_id IN (SELECT gm.group_id FROM public.group_members gm WHERE gm.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "Allow members to update group expenses" ON public.expenses;
CREATE POLICY "Allow members to update group expenses"
  ON public.expenses FOR UPDATE TO authenticated
  USING (
    group_id IN (SELECT gm.group_id FROM public.group_members gm WHERE gm.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "Allow members to delete group expenses" ON public.expenses;
CREATE POLICY "Allow members to delete group expenses"
  ON public.expenses FOR DELETE TO authenticated
  USING (
    group_id IN (SELECT gm.group_id FROM public.group_members gm WHERE gm.user_id = auth.uid())
  );

-- 3.5 Expense Splits Policies
DROP POLICY IF EXISTS "Allow members to view splits for group expenses" ON public.expense_splits;
CREATE POLICY "Allow members to view splits for group expenses"
  ON public.expense_splits FOR SELECT TO authenticated
  USING (
    expense_id IN (
      SELECT e.id FROM public.expenses e
      WHERE e.group_id IN (SELECT gm.group_id FROM public.group_members gm WHERE gm.user_id = auth.uid())
    )
  );

DROP POLICY IF EXISTS "Allow members to create splits for group expenses" ON public.expense_splits;
CREATE POLICY "Allow members to create splits for group expenses"
  ON public.expense_splits FOR INSERT TO authenticated
  WITH CHECK (
    expense_id IN (
      SELECT e.id FROM public.expenses e
      WHERE e.group_id IN (SELECT gm.group_id FROM public.group_members gm WHERE gm.user_id = auth.uid())
    )
  );

DROP POLICY IF EXISTS "Allow members to update splits for group expenses" ON public.expense_splits;
CREATE POLICY "Allow members to update splits for group expenses"
  ON public.expense_splits FOR UPDATE TO authenticated
  USING (
    expense_id IN (
      SELECT e.id FROM public.expenses e
      WHERE e.group_id IN (SELECT gm.group_id FROM public.group_members gm WHERE gm.user_id = auth.uid())
    )
  );

DROP POLICY IF EXISTS "Allow members to delete splits for group expenses" ON public.expense_splits;
CREATE POLICY "Allow members to delete splits for group expenses"
  ON public.expense_splits FOR DELETE TO authenticated
  USING (
    expense_id IN (
      SELECT e.id FROM public.expenses e
      WHERE e.group_id IN (SELECT gm.group_id FROM public.group_members gm WHERE gm.user_id = auth.uid())
    )
  );

-- 3.6 Settlements Policies
DROP POLICY IF EXISTS "Allow members to view group settlements" ON public.settlements;
CREATE POLICY "Allow members to view group settlements"
  ON public.settlements FOR SELECT TO authenticated
  USING (
    group_id IN (SELECT gm.group_id FROM public.group_members gm WHERE gm.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "Allow members to create group settlements" ON public.settlements;
CREATE POLICY "Allow members to create group settlements"
  ON public.settlements FOR INSERT TO authenticated
  WITH CHECK (
    group_id IN (SELECT gm.group_id FROM public.group_members gm WHERE gm.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "Allow members to update group settlements" ON public.settlements;
CREATE POLICY "Allow members to update group settlements"
  ON public.settlements FOR UPDATE TO authenticated
  USING (
    group_id IN (SELECT gm.group_id FROM public.group_members gm WHERE gm.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "Allow members to delete group settlements" ON public.settlements;
CREATE POLICY "Allow members to delete group settlements"
  ON public.settlements FOR DELETE TO authenticated
  USING (
    group_id IN (SELECT gm.group_id FROM public.group_members gm WHERE gm.user_id = auth.uid())
  );

---------------------------------------------------------
-- 4. STORAGE POLICIES
---------------------------------------------------------

-- SELECT POLICY FOR STORAGE
DROP POLICY IF EXISTS "Allow group members to view group receipts" ON storage.objects;
CREATE POLICY "Allow group members to view group receipts" 
ON storage.objects FOR SELECT TO authenticated 
USING (
  bucket_id = 'receipts' AND 
  public.safe_cast_uuid(split_part(name, '/', 1)) IN (
    SELECT group_id FROM public.group_members WHERE user_id = auth.uid()
  )
);

-- INSERT POLICY FOR STORAGE
DROP POLICY IF EXISTS "Allow group members to upload group receipts" ON storage.objects;
CREATE POLICY "Allow group members to upload group receipts" 
ON storage.objects FOR INSERT TO authenticated 
WITH CHECK (
  bucket_id = 'receipts' AND 
  public.safe_cast_uuid(split_part(name, '/', 1)) IN (
    SELECT group_id FROM public.group_members WHERE user_id = auth.uid()
  )
);

-- DELETE POLICY FOR STORAGE
DROP POLICY IF EXISTS "Allow group members to delete group receipts" ON storage.objects;
CREATE POLICY "Allow group members to delete group receipts" 
ON storage.objects FOR DELETE TO authenticated 
USING (
  bucket_id = 'receipts' AND 
  public.safe_cast_uuid(split_part(name, '/', 1)) IN (
    SELECT group_id FROM public.group_members WHERE user_id = auth.uid()
  )
);
